#!/bin/bash

#iniciar servidor
if [ "$1" == "run" ]; then
    python3 app.py

elif [ "$1" == "test" ]; then
    python3 app.py & SERVER_PID=$!
    pytest -s
    TESTS_EXIT_CODE=$?
    kill $SERVER_PID
    exit $TESTS_EXIT_CODE
    
else
    echo "Command not found... <NutriJ>"

fi