#!/bin/bash

# Iniciar servidor
if [ "$1" == "run" ]; then
    python3 app.py

# Iniciar base de datos
elif [ "$1" == "dbstart" ]; then
    pg_ctl -D /usr/local/var/postgres start 

# Parar base de datos
elif [ "$1" == "dbstop" ]; then
    pg_ctl -D /usr/local/var/postgres stop   

# Servidor, tests y cerrar
elif [ "$1" == "test" ]; then
    python3 app.py & SERVER_PID=$!
    pytest -s
    TESTS_EXIT_CODE=$?
    kill $SERVER_PID
    exit $TESTS_EXIT_CODE
    
else
    echo "Command not found... <NutriJ>"

fi